-- Drop in reverse order to avoid FK conflicts on restarts
drop table if exists Ingredient_Ref;
drop table if exists Taco;
drop table if exists Taco_Order;
drop table if exists Ingredient;

-- Ingredient must have a PK for FK references
create table Ingredient (
                            id   varchar(4)  primary key,
                            name varchar(25) not null,
                            type varchar(10) not null
);

create table Taco_Order (
                            id               bigint generated by default as identity primary key,
                            delivery_name    varchar(50) not null,
                            delivery_street  varchar(50) not null,
                            delivery_city    varchar(50) not null,
                            delivery_state   varchar(10) not null,
                            delivery_zip     varchar(10) not null,
                            cc_number        varchar(19) not null,
                            cc_expiration    varchar(7)  not null,
                            cc_cvv           varchar(4)  not null,
                            placed_at        timestamp   not null
);

create table Taco (
                      id             bigint generated by default as identity primary key,
                      name           varchar(50) not null,
                      taco_order     bigint,
                      taco_order_key bigint,
                      created_at     timestamp   not null
);

create table Ingredient_Ref (
                                ingredient varchar(4) not null,
                                taco       bigint     not null,
                                taco_key   bigint     not null
);

-- Foreign keys after tables exist
alter table Taco
    add constraint fk_taco_order
        foreign key (taco_order) references Taco_Order(id);

alter table Ingredient_Ref
    add constraint fk_ingref_ingredient
        foreign key (ingredient) references Ingredient(id);

alter table Ingredient_Ref
    add constraint fk_ingref_taco
        foreign key (taco) references Taco(id);
